# Generated by Django 4.0.3 on 2022-03-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='produto',
        ),
    ]
