# Generated by Django 4.0.3 on 2022-03-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_variacao_produto'),
    ]

    operations = [
        migrations.DeleteModel('Variacao')
    ]
