# Generated by Django 4.0.3 on 2022-03-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20220324_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
