# Generated by Django 4.0.3 on 2022-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='UN', max_length=30),
        ),
    ]
