# Generated by Django 4.0.3 on 2022-03-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoitem',
            name='solicitacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solicitacao.solicitacao'),
            preserve_default=False,
        ),
    ]
