# Generated by Django 4.0.3 on 2022-03-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
        ('solicitacao', '0002_solicitacaoitem_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='secretaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='secretaria.secretaria'),
            preserve_default=False,
        ),
    ]
