# Generated by Django 4.0.3 on 2022-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_solicitacao_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(default='2022-03-23', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
