# Generated by Django 4.0.3 on 2022-03-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_solicitacao_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoitem',
            options={'verbose_name': 'Item da Solicitação', 'verbose_name_plural': 'Itens da Solicitação'},
        ),
    ]
