# Generated by Django 4.0.3 on 2022-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_alter_solicitacaoitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='objeto',
            field=models.TextField(blank=True, null=True, verbose_name='Objeto'),
        ),
    ]
