# Generated by Django 4.0.3 on 2022-03-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_solicitacao_objeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoitem',
            name='variacao',
        ),
        migrations.RemoveField(
            model_name='solicitacaoitem',
            name='variacao_id',
        ),
    ]
