# Generated by Django 4.0.3 on 2022-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0008_alter_solicitacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
