# Generated by Django 4.0.3 on 2022-04-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_alter_solicitacaoitem_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='qtd_total',
        ),
    ]
