# Generated by Django 4.0.3 on 2022-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0011_solicitacaoquantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoquantidade',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='solicitacaoitem',
            name='qtd',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantidade'),
        ),
    ]
