# Generated by Django 4.0.3 on 2022-04-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0011_solicitacaoquantidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.RemoveField(
            model_name='solicitacaoquantidade',
            name='quantidade',
        ),
    ]
