# Generated by Django 4.0.3 on 2022-04-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0012_remove_solicitacaoquantidade_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoquantidade',
            options={},
        ),
    ]
