# Generated by Django 4.0.3 on 2022-04-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0013_alter_solicitacaoquantidade_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoitem',
            name='produto',
        ),
    ]
