# Generated by Django 4.0.3 on 2022-04-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0014_remove_solicitacaoitem_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoitem',
            name='produto_id',
        ),
    ]
