# Generated by Django 4.0.3 on 2022-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
