# Generated by Django 4.0.3 on 2022-03-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeitura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefeitura',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logotipo'),
        ),
    ]
