# Generated by Django 4.0.3 on 2022-03-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeitura', '0003_alter_prefeitura_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefeitura',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
