# Generated by Django 4.0.3 on 2022-03-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefeitura', '0005_alter_prefeitura_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefeitura',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='prefeitura/%Y/%m', verbose_name='Logotipo'),
        ),
    ]
