# Generated by Django 4.0.3 on 2022-03-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefeitura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('secretario', models.CharField(max_length=120)),
                ('ativo', models.BooleanField()),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefeitura.prefeitura')),
            ],
        ),
    ]
