# Generated by Django 4.0.3 on 2022-03-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaria',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
